version: '3.8'

services:
  web:
    image: nginx
    volumes:
      - ./html:/usr/share/nginx/html
    ports:
      - "8081:80"
    networks:
      - mynet

  redis:
    image: redis
    networks:
      - mynet

  app:
    image: alpine
    environment:
      - MESSAGE=Hello from Alpine!
    command: sh -c "while true; do echo $MESSAGE; sleep 5; done"
    networks:
      - mynet

networks:
  mynet:

